id: P000612
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24726
  title: ལག་ལེན་བདུད་རྩིའི་གཏེར་སྒྲོམ། མན་ངག་བདུད་རྩིའི་བུམ་བཟང།
  author: ''
  volumes:
    83c31a47cdd94179b744cb46bd968499:
      image_group_id: I1KG24728
      title: ''
      volume_number: 1
      total_pages: 279
