id: P000612
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:51:31.917195
source_metadata:
  id: bdr:W1KG24726
  title: ལག་ལེན་བདུད་རྩིའི་གཏེར་སྒྲོམ། མན་ངག་བདུད་རྩིའི་བུམ་བཟང།
  author: ''
  volumes:
    83c31a47cdd94179b744cb46bd968499:
      image_group_id: I1KG24728
      title: ''
      volume_number: 1
      total_pages: 279
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
